var constants = {
  ADD_TODO: "ADD_TODO",
  TOGGLE_TODO: "TOGGLE_TODO",
  CLEAR_TODOS: "CLEAR_TODOS",
  FILTER_PRODUCTS: "FILTER_PRODUCTS",
  GET_PRODUCTS: "GET_PRODUCTS"
};

module.exports = constants;